//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAVIGEST.Shared.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NAVIGEST.Shared.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ClientsPage_Title {
            get {
                return ResourceManager.GetString("ClientsPage_Title", resourceCulture);
            }
        }
        
        public static string ClientsPage_NewClient {
            get {
                return ResourceManager.GetString("ClientsPage_NewClient", resourceCulture);
            }
        }

        public static string ClientsPage_AddClient {
            get {
                return ResourceManager.GetString("ClientsPage_AddClient", resourceCulture);
            }
        }

        public static string ClientsPage_EditClient {
            get {
                return ResourceManager.GetString("ClientsPage_EditClient", resourceCulture);
            }
        }

        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }

        public static string Common_Update {
            get {
                return ResourceManager.GetString("Common_Update", resourceCulture);
            }
        }

        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }

        public static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }

        public static string Common_SearchPlaceholder {
            get {
                return ResourceManager.GetString("Common_SearchPlaceholder", resourceCulture);
            }
        }

        public static string Common_Name {
            get {
                return ResourceManager.GetString("Common_Name", resourceCulture);
            }
        }

        public static string Common_Code {
            get {
                return ResourceManager.GetString("Common_Code", resourceCulture);
            }
        }

        public static string Common_Phone {
            get {
                return ResourceManager.GetString("Common_Phone", resourceCulture);
            }
        }

        public static string Common_Email {
            get {
                return ResourceManager.GetString("Common_Email", resourceCulture);
            }
        }

        public static string ClientsPage_Salesperson {
            get {
                return ResourceManager.GetString("ClientsPage_Salesperson", resourceCulture);
            }
        }

        public static string ClientsPage_ClientNamePlaceholder {
            get {
                return ResourceManager.GetString("ClientsPage_ClientNamePlaceholder", resourceCulture);
            }
        }

        public static string ClientsPage_CreditValue {
            get {
                return ResourceManager.GetString("ClientsPage_CreditValue", resourceCulture);
            }
        }

        public static string ClientsPage_ExternalLabel {
            get {
                return ResourceManager.GetString("ClientsPage_ExternalLabel", resourceCulture);
            }
        }

        public static string ClientsPage_CancelledLabel {
            get {
                return ResourceManager.GetString("ClientsPage_CancelledLabel", resourceCulture);
            }
        }

        public static string ClientsPage_SyncedFolders {
            get {
                return ResourceManager.GetString("ClientsPage_SyncedFolders", resourceCulture);
            }
        }
        
        public static string ClientsPage_External {
             get {
                 return ResourceManager.GetString("ClientsPage_External", resourceCulture);
             }
        }

        public static string ClientsPage_Cancelled {
             get {
                 return ResourceManager.GetString("ClientsPage_Cancelled", resourceCulture);
             }
        }

        public static string ProductsPage_Title {
            get {
                return ResourceManager.GetString("ProductsPage_Title", resourceCulture);
            }
        }

        public static string ProductsPage_NewProduct {
            get {
                return ResourceManager.GetString("ProductsPage_NewProduct", resourceCulture);
            }
        }

        public static string ProductsPage_SearchPlaceholder {
            get {
                return ResourceManager.GetString("ProductsPage_SearchPlaceholder", resourceCulture);
            }
        }

        public static string Common_Cost {
            get {
                return ResourceManager.GetString("Common_Cost", resourceCulture);
            }
        }

        public static string Common_Sale {
            get {
                return ResourceManager.GetString("Common_Sale", resourceCulture);
            }
        }

        public static string Common_TotalSales {
            get {
                return ResourceManager.GetString("Common_TotalSales", resourceCulture);
            }
        }

        public static string Common_Collaborator {
            get {
                return ResourceManager.GetString("Common_Collaborator", resourceCulture);
            }
        }

        public static string Common_Description {
            get {
                return ResourceManager.GetString("Common_Description", resourceCulture);
            }
        }

        public static string Common_Family {
            get {
                return ResourceManager.GetString("Common_Family", resourceCulture);
            }
        }

        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }

        public static string Common_Search {
            get {
                return ResourceManager.GetString("Common_Search", resourceCulture);
            }
        }

        public static string ProductsPage_CostPrice {
            get {
                return ResourceManager.GetString("ProductsPage_CostPrice", resourceCulture);
            }
        }

        public static string ProductsPage_SalePrice {
            get {
                return ResourceManager.GetString("ProductsPage_SalePrice", resourceCulture);
            }
        }

        public static string ProductsPage_ProductDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("ProductsPage_ProductDescriptionPlaceholder", resourceCulture);
            }
        }

        public static string ProductsPage_SelectFamily {
            get {
                return ResourceManager.GetString("ProductsPage_SelectFamily", resourceCulture);
            }
        }

        public static string ProductsPage_AddFamily {
            get {
                return ResourceManager.GetString("ProductsPage_AddFamily", resourceCulture);
            }
        }

        public static string ProductsPage_NewFamily {
            get {
                return ResourceManager.GetString("ProductsPage_NewFamily", resourceCulture);
            }
        }

        public static string ProductsPage_FamilyCodePlaceholder {
            get {
                return ResourceManager.GetString("ProductsPage_FamilyCodePlaceholder", resourceCulture);
            }
        }

        public static string ProductsPage_FamilyDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("ProductsPage_FamilyDescriptionPlaceholder", resourceCulture);
            }
        }

        public static string Hours_EditTitle {
            get {
                return ResourceManager.GetString("Hours_EditTitle", resourceCulture);
            }
        }
        public static string Hours_NewTitle {
            get {
                return ResourceManager.GetString("Hours_NewTitle", resourceCulture);
            }
        }
        public static string Family_NewTitle {
            get {
                return ResourceManager.GetString("Family_NewTitle", resourceCulture);
            }
        }
        public static string Family_NamePlaceholder {
            get {
                return ResourceManager.GetString("Family_NamePlaceholder", resourceCulture);
            }
        }
        public static string Sync_FolderTitle {
            get {
                return ResourceManager.GetString("Sync_FolderTitle", resourceCulture);
            }
        }
        public static string Sync_FolderMessage {
            get {
                return ResourceManager.GetString("Sync_FolderMessage", resourceCulture);
            }
        }
        public static string Sync_Yes {
            get {
                return ResourceManager.GetString("Sync_Yes", resourceCulture);
            }
        }
        public static string Sync_NotNow {
            get {
                return ResourceManager.GetString("Sync_NotNow", resourceCulture);
            }
        }
        public static string Sync_ReportTitle {
            get {
                return ResourceManager.GetString("Sync_ReportTitle", resourceCulture);
            }
        }
        public static string Sync_ReportMessage {
            get {
                return ResourceManager.GetString("Sync_ReportMessage", resourceCulture);
            }
        }
        public static string Sync_Starting {
            get {
                return ResourceManager.GetString("Sync_Starting", resourceCulture);
            }
        }
        public static string Dashboard_TotalHours {
            get {
                return ResourceManager.GetString("Dashboard_TotalHours", resourceCulture);
            }
        }
        public static string Dashboard_DailyAverage {
            get {
                return ResourceManager.GetString("Dashboard_DailyAverage", resourceCulture);
            }
        }
        public static string Dashboard_WorkedDays {
            get {
                return ResourceManager.GetString("Dashboard_WorkedDays", resourceCulture);
            }
        }
        public static string Dashboard_TopClients {
            get {
                return ResourceManager.GetString("Dashboard_TopClients", resourceCulture);
            }
        }
        public static string Dashboard_TopFamilies {
            get {
                return ResourceManager.GetString("Dashboard_TopFamilies", resourceCulture);
            }
        }
        public static string Dashboard_HoursByMonth {
            get {
                return ResourceManager.GetString("Dashboard_HoursByMonth", resourceCulture);
            }
        }
        public static string Dashboard_HoursByFamily {
            get {
                return ResourceManager.GetString("Dashboard_HoursByFamily", resourceCulture);
            }
        }
        public static string Dashboard_Balance {
            get {
                return ResourceManager.GetString("Dashboard_Balance", resourceCulture);
            }
        }
        public static string Dashboard_Evolution {
            get {
                return ResourceManager.GetString("Dashboard_Evolution", resourceCulture);
            }
        }
        public static string Dashboard_Annual {
            get {
                return ResourceManager.GetString("Dashboard_Annual", resourceCulture);
            }
        }
        public static string Dashboard_RealHours {
            get {
                return ResourceManager.GetString("Dashboard_RealHours", resourceCulture);
            }
        }
        public static string Dashboard_IdealHours {
            get {
                return ResourceManager.GetString("Dashboard_IdealHours", resourceCulture);
            }
        }
        public static string Dashboard_ExtraHours {
            get {
                return ResourceManager.GetString("Dashboard_ExtraHours", resourceCulture);
            }
        }
        public static string Dashboard_Absences {
            get {
                return ResourceManager.GetString("Dashboard_Absences", resourceCulture);
            }
        }
        public static string Dashboard_AbsencesAccumulated {
            get {
                return ResourceManager.GetString("Dashboard_AbsencesAccumulated", resourceCulture);
            }
        }
        public static string Dashboard_SelectCollaborator {
            get {
                return ResourceManager.GetString("Dashboard_SelectCollaborator", resourceCulture);
            }
        }
        public static string Common_DeleteConfirmationTitle {
            get {
                return ResourceManager.GetString("Common_DeleteConfirmationTitle", resourceCulture);
            }
        }
        public static string Common_DeleteConfirmationMessage {
            get {
                return ResourceManager.GetString("Common_DeleteConfirmationMessage", resourceCulture);
            }
        }
        public static string Common_DeleteConfirmationMessageFormat {
            get {
                return ResourceManager.GetString("Common_DeleteConfirmationMessageFormat", resourceCulture);
            }
        }
        public static string Hours_SelectCollaborator {
            get {
                return ResourceManager.GetString("Hours_SelectCollaborator", resourceCulture);
            }
        }
        public static string Hours_Absence {
            get {
                return ResourceManager.GetString("Hours_Absence", resourceCulture);
            }
        }
        public static string Hours_SelectReason {
            get {
                return ResourceManager.GetString("Hours_SelectReason", resourceCulture);
            }
        }
        public static string Hours_NoClient {
            get {
                return ResourceManager.GetString("Hours_NoClient", resourceCulture);
            }
        }
        public static string Hours_Work {
            get {
                return ResourceManager.GetString("Hours_Work", resourceCulture);
            }
        }
        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }

        public static string Welcome_Connecting {
            get {
                return ResourceManager.GetString("Welcome_Connecting", resourceCulture);
            }
        }

        public static string Welcome_ConnectionFailed {
            get {
                return ResourceManager.GetString("Welcome_ConnectionFailed", resourceCulture);
            }
        }

        public static string Welcome_ConnectionError {
            get {
                return ResourceManager.GetString("Welcome_ConnectionError", resourceCulture);
            }
        }

        public static string Welcome_Title {
            get {
                return ResourceManager.GetString("Welcome_Title", resourceCulture);
            }
        }

        public static string Welcome_Subtitle {
            get {
                return ResourceManager.GetString("Welcome_Subtitle", resourceCulture);
            }
        }

        public static string Welcome_Description {
            get {
                return ResourceManager.GetString("Welcome_Description", resourceCulture);
            }
        }

        public static string Welcome_ChooseCompany {
            get {
                return ResourceManager.GetString("Welcome_ChooseCompany", resourceCulture);
            }
        }

        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }

        public static string Login_Welcome {
            get {
                return ResourceManager.GetString("Login_Welcome", resourceCulture);
            }
        }

        public static string Login_UserFound {
            get {
                return ResourceManager.GetString("Login_UserFound", resourceCulture);
            }
        }

        public static string Login_Subtitle {
            get {
                return ResourceManager.GetString("Login_Subtitle", resourceCulture);
            }
        }

        public static string Login_UsernamePlaceholder {
            get {
                return ResourceManager.GetString("Login_UsernamePlaceholder", resourceCulture);
            }
        }

        public static string Login_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("Login_PasswordPlaceholder", resourceCulture);
            }
        }

        public static string Login_Button {
            get {
                return ResourceManager.GetString("Login_Button", resourceCulture);
            }
        }

        public static string Login_Biometric {
            get {
                return ResourceManager.GetString("Login_Biometric", resourceCulture);
            }
        }

        public static string Login_RememberMe {
            get {
                return ResourceManager.GetString("Login_RememberMe", resourceCulture);
            }
        }

        public static string Login_ForgotPassword {
            get {
                return ResourceManager.GetString("Login_ForgotPassword", resourceCulture);
            }
        }

        public static string Login_HaveCode {
            get {
                return ResourceManager.GetString("Login_HaveCode", resourceCulture);
            }
        }

        public static string Login_InternalReset {
            get {
                return ResourceManager.GetString("Login_InternalReset", resourceCulture);
            }
        }

        public static string Login_InvalidCredentials {
            get {
                return ResourceManager.GetString("Login_InvalidCredentials", resourceCulture);
            }
        }

        public static string Main_Logout {
            get {
                return ResourceManager.GetString("Main_Logout", resourceCulture);
            }
        }

        public static string Main_Dashboard {
            get {
                return ResourceManager.GetString("Main_Dashboard", resourceCulture);
            }
        }

        public static string Main_Clients {
            get {
                return ResourceManager.GetString("Main_Clients", resourceCulture);
            }
        }

        public static string Main_Products {
            get {
                return ResourceManager.GetString("Main_Products", resourceCulture);
            }
        }

        public static string Main_Hours {
            get {
                return ResourceManager.GetString("Main_Hours", resourceCulture);
            }
        }

        public static string Main_Services {
            get {
                return ResourceManager.GetString("Main_Services", resourceCulture);
            }
        }

        public static string Main_Theme {
            get {
                return ResourceManager.GetString("Main_Theme", resourceCulture);
            }
        }

        public static string Main_ThemeAuto {
            get {
                return ResourceManager.GetString("Main_ThemeAuto", resourceCulture);
            }
        }

        public static string Main_ThemeLight {
            get {
                return ResourceManager.GetString("Main_ThemeLight", resourceCulture);
            }
        }

        public static string Main_ThemeDark {
            get {
                return ResourceManager.GetString("Main_ThemeDark", resourceCulture);
            }
        }

        public static string Main_WelcomeTo {
            get {
                return ResourceManager.GetString("Main_WelcomeTo", resourceCulture);
            }
        }

        public static string Main_AdminAccess {
            get {
                return ResourceManager.GetString("Main_AdminAccess", resourceCulture);
            }
        }

        public static string Main_AdminUserPlaceholder {
            get {
                return ResourceManager.GetString("Main_AdminUserPlaceholder", resourceCulture);
            }
        }

        public static string Main_AdminPassPlaceholder {
            get {
                return ResourceManager.GetString("Main_AdminPassPlaceholder", resourceCulture);
            }
        }

        public static string Main_LogoutTitle {
            get {
                return ResourceManager.GetString("Main_LogoutTitle", resourceCulture);
            }
        }

        public static string Main_LogoutMessage {
            get {
                return ResourceManager.GetString("Main_LogoutMessage", resourceCulture);
            }
        }

        public static string Main_LogoutConfirm {
            get {
                return ResourceManager.GetString("Main_LogoutConfirm", resourceCulture);
            }
        }

        public static string Main_CloseTitle {
            get {
                return ResourceManager.GetString("Main_CloseTitle", resourceCulture);
            }
        }

        public static string Main_CloseMessage {
            get {
                return ResourceManager.GetString("Main_CloseMessage", resourceCulture);
            }
        }

        public static string Main_AccessDenied {
            get {
                return ResourceManager.GetString("Main_AccessDenied", resourceCulture);
            }
        }

        public static string Main_AdminRequired {
            get {
                return ResourceManager.GetString("Main_AdminRequired", resourceCulture);
            }
        }

        public static string Main_AdminEnterCredentials {
            get {
                return ResourceManager.GetString("Main_AdminEnterCredentials", resourceCulture);
            }
        }

        public static string Main_NoContent {
            get {
                return ResourceManager.GetString("Main_NoContent", resourceCulture);
            }
        }

        public static string Common_Back {
            get {
                return ResourceManager.GetString("Common_Back", resourceCulture);
            }
        }

        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }

        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }

        public static string Settings_SystemSettings {
            get {
                return ResourceManager.GetString("Settings_SystemSettings", resourceCulture);
            }
        }

        public static string Settings_Users {
            get {
                return ResourceManager.GetString("Settings_Users", resourceCulture);
            }
        }

        public static string Settings_UsersDesc {
            get {
                return ResourceManager.GetString("Settings_UsersDesc", resourceCulture);
            }
        }

        public static string Settings_Database {
            get {
                return ResourceManager.GetString("Settings_Database", resourceCulture);
            }
        }

        public static string Settings_DatabaseDesc {
            get {
                return ResourceManager.GetString("Settings_DatabaseDesc", resourceCulture);
            }
        }

        public static string Settings_FileServer {
            get {
                return ResourceManager.GetString("Settings_FileServer", resourceCulture);
            }
        }

        public static string Settings_FileServerDesc {
            get {
                return ResourceManager.GetString("Settings_FileServerDesc", resourceCulture);
            }
        }

        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }

        public static string Settings_LanguageDesc {
            get {
                return ResourceManager.GetString("Settings_LanguageDesc", resourceCulture);
            }
        }

        public static string Login_UseBiometric {
            get {
                return ResourceManager.GetString("Login_UseBiometric", resourceCulture);
            }
        }

        public static string Hours_TabSummary {
            get {
                return ResourceManager.GetString("Hours_TabSummary", resourceCulture);
            }
        }
        public static string Hours_TabList {
            get {
                return ResourceManager.GetString("Hours_TabList", resourceCulture);
            }
        }
        public static string Hours_TabCalendar {
            get {
                return ResourceManager.GetString("Hours_TabCalendar", resourceCulture);
            }
        }
        public static string Hours_DailySummary {
            get {
                return ResourceManager.GetString("Hours_DailySummary", resourceCulture);
            }
        }
        public static string Hours_NormalHours {
            get {
                return ResourceManager.GetString("Hours_NormalHours", resourceCulture);
            }
        }
        public static string Hours_ExtraHours {
            get {
                return ResourceManager.GetString("Hours_ExtraHours", resourceCulture);
            }
        }
        public static string Hours_Total {
            get {
                return ResourceManager.GetString("Hours_Total", resourceCulture);
            }
        }
        public static string Hours_Weekend {
            get {
                return ResourceManager.GetString("Hours_Weekend", resourceCulture);
            }
        }
        public static string Hours_NoRecords {
            get {
                return ResourceManager.GetString("Hours_NoRecords", resourceCulture);
            }
        }
        public static string Hours_SelectPeriod {
            get {
                return ResourceManager.GetString("Hours_SelectPeriod", resourceCulture);
            }
        }
        public static string Hours_PeriodToday {
            get {
                return ResourceManager.GetString("Hours_PeriodToday", resourceCulture);
            }
        }
        public static string Hours_PeriodThisWeek {
            get {
                return ResourceManager.GetString("Hours_PeriodThisWeek", resourceCulture);
            }
        }
        public static string Hours_PeriodThisMonth {
            get {
                return ResourceManager.GetString("Hours_PeriodThisMonth", resourceCulture);
            }
        }
        public static string Hours_PeriodLast30Days {
            get {
                return ResourceManager.GetString("Hours_PeriodLast30Days", resourceCulture);
            }
        }
        public static string Hours_CalendarMonth {
            get {
                return ResourceManager.GetString("Hours_CalendarMonth", resourceCulture);
            }
        }
        public static string Hours_LegendNormal {
            get {
                return ResourceManager.GetString("Hours_LegendNormal", resourceCulture);
            }
        }
        public static string Hours_LegendExtra {
            get {
                return ResourceManager.GetString("Hours_LegendExtra", resourceCulture);
            }
        }
        public static string Hours_Reason {
            get {
                return ResourceManager.GetString("Hours_Reason", resourceCulture);
            }
        }
        public static string Hours_Client {
            get {
                return ResourceManager.GetString("Hours_Client", resourceCulture);
            }
        }
        public static string Hours_Date {
            get {
                return ResourceManager.GetString("Hours_Date", resourceCulture);
            }
        }
        public static string Hours_Observations {
            get {
                return ResourceManager.GetString("Hours_Observations", resourceCulture);
            }
        }
        public static string Hours_SelectClient {
            get {
                return ResourceManager.GetString("Hours_SelectClient", resourceCulture);
            }
        }
        public static string Hours_RecordType {
            get {
                return ResourceManager.GetString("Hours_RecordType", resourceCulture);
            }
        }
        public static string Hours_SavedSuccess {
            get {
                return ResourceManager.GetString("Hours_SavedSuccess", resourceCulture);
            }
        }
        public static string Hours_ErrorSelectCollaborator {
            get {
                return ResourceManager.GetString("Hours_ErrorSelectCollaborator", resourceCulture);
            }
        }
        public static string Hours_ErrorSelectReason {
            get {
                return ResourceManager.GetString("Hours_ErrorSelectReason", resourceCulture);
            }
        }
        public static string Hours_ErrorEnterHours {
            get {
                return ResourceManager.GetString("Hours_ErrorEnterHours", resourceCulture);
            }
        }
        public static string Hours_ErrorSaving {
            get {
                return ResourceManager.GetString("Hours_ErrorSaving", resourceCulture);
            }
        }
        public static string Hours_ErrorOpeningPopup {
            get {
                return ResourceManager.GetString("Hours_ErrorOpeningPopup", resourceCulture);
            }
        }
    

        public static string AboutPage_AppVersion {
            get {
                return ResourceManager.GetString("AboutPage_AppVersion", resourceCulture);
            }
        }

        public static string AboutPage_CheckNotes {
            get {
                return ResourceManager.GetString("AboutPage_CheckNotes", resourceCulture);
            }
        }

        public static string AboutPage_CheckUpdates {
            get {
                return ResourceManager.GetString("AboutPage_CheckUpdates", resourceCulture);
            }
        }

        public static string AboutPage_CheckingUpdates {
            get {
                return ResourceManager.GetString("AboutPage_CheckingUpdates", resourceCulture);
            }
        }

        public static string AboutPage_Info {
            get {
                return ResourceManager.GetString("AboutPage_Info", resourceCulture);
            }
        }

        public static string AboutPage_Later {
            get {
                return ResourceManager.GetString("AboutPage_Later", resourceCulture);
            }
        }

        public static string AboutPage_MandatoryUpdatePrefix {
            get {
                return ResourceManager.GetString("AboutPage_MandatoryUpdatePrefix", resourceCulture);
            }
        }

        public static string AboutPage_MandatoryUpdateTitle {
            get {
                return ResourceManager.GetString("AboutPage_MandatoryUpdateTitle", resourceCulture);
            }
        }

        public static string AboutPage_NewVersionAvailable {
            get {
                return ResourceManager.GetString("AboutPage_NewVersionAvailable", resourceCulture);
            }
        }

        public static string AboutPage_Platform {
            get {
                return ResourceManager.GetString("AboutPage_Platform", resourceCulture);
            }
        }

        public static string AboutPage_Title {
            get {
                return ResourceManager.GetString("AboutPage_Title", resourceCulture);
            }
        }

        public static string AboutPage_Update {
            get {
                return ResourceManager.GetString("AboutPage_Update", resourceCulture);
            }
        }

        public static string AboutPage_UpdateAvailableTitle {
            get {
                return ResourceManager.GetString("AboutPage_UpdateAvailableTitle", resourceCulture);
            }
        }

        public static string AboutPage_UpdateError {
            get {
                return ResourceManager.GetString("AboutPage_UpdateError", resourceCulture);
            }
        }

        public static string AboutPage_UpdateInfoError {
            get {
                return ResourceManager.GetString("AboutPage_UpdateInfoError", resourceCulture);
            }
        }

        public static string AboutPage_UpdateNow {
            get {
                return ResourceManager.GetString("AboutPage_UpdateNow", resourceCulture);
            }
        }

        public static string Absence_AddNew {
            get {
                return ResourceManager.GetString("Absence_AddNew", resourceCulture);
            }
        }

        public static string Absence_ConfirmDelete {
            get {
                return ResourceManager.GetString("Absence_ConfirmDelete", resourceCulture);
            }
        }

        public static string Absence_DescriptionLabel {
            get {
                return ResourceManager.GetString("Absence_DescriptionLabel", resourceCulture);
            }
        }

        public static string Absence_EditTypeTitle {
            get {
                return ResourceManager.GetString("Absence_EditTypeTitle", resourceCulture);
            }
        }

        public static string Absence_EmptyList {
            get {
                return ResourceManager.GetString("Absence_EmptyList", resourceCulture);
            }
        }

        public static string Absence_ErrorEmptyDescription {
            get {
                return ResourceManager.GetString("Absence_ErrorEmptyDescription", resourceCulture);
            }
        }

        public static string Absence_NewTypeMessage {
            get {
                return ResourceManager.GetString("Absence_NewTypeMessage", resourceCulture);
            }
        }

        public static string Absence_NewTypeTitle {
            get {
                return ResourceManager.GetString("Absence_NewTypeTitle", resourceCulture);
            }
        }

        public static string Absence_Title {
            get {
                return ResourceManager.GetString("Absence_Title", resourceCulture);
            }
        }

        public static string ClientsPage_AddedSuccess {
            get {
                return ResourceManager.GetString("ClientsPage_AddedSuccess", resourceCulture);
            }
        }

        public static string ClientsPage_ClientNotFound {
            get {
                return ResourceManager.GetString("ClientsPage_ClientNotFound", resourceCulture);
            }
        }

        public static string ClientsPage_DeleteBlocked {
            get {
                return ResourceManager.GetString("ClientsPage_DeleteBlocked", resourceCulture);
            }
        }

        public static string ClientsPage_DeleteConfirm {
            get {
                return ResourceManager.GetString("ClientsPage_DeleteConfirm", resourceCulture);
            }
        }

        public static string ClientsPage_DeleteConfirmTitle {
            get {
                return ResourceManager.GetString("ClientsPage_DeleteConfirmTitle", resourceCulture);
            }
        }

        public static string ClientsPage_DeleteTitle {
            get {
                return ResourceManager.GetString("ClientsPage_DeleteTitle", resourceCulture);
            }
        }

        public static string ClientsPage_DeletedSuccess {
            get {
                return ResourceManager.GetString("ClientsPage_DeletedSuccess", resourceCulture);
            }
        }

        public static string ClientsPage_ErrorDelete {
            get {
                return ResourceManager.GetString("ClientsPage_ErrorDelete", resourceCulture);
            }
        }

        public static string ClientsPage_ErrorEdit {
            get {
                return ResourceManager.GetString("ClientsPage_ErrorEdit", resourceCulture);
            }
        }

        public static string ClientsPage_ErrorFolders {
            get {
                return ResourceManager.GetString("ClientsPage_ErrorFolders", resourceCulture);
            }
        }

        public static string ClientsPage_ErrorSave {
            get {
                return ResourceManager.GetString("ClientsPage_ErrorSave", resourceCulture);
            }
        }

        public static string ClientsPage_InvalidClientCode {
            get {
                return ResourceManager.GetString("ClientsPage_InvalidClientCode", resourceCulture);
            }
        }

        public static string ClientsPage_LoadError {
            get {
                return ResourceManager.GetString("ClientsPage_LoadError", resourceCulture);
            }
        }

        public static string ClientsPage_NameRequired {
            get {
                return ResourceManager.GetString("ClientsPage_NameRequired", resourceCulture);
            }
        }

        public static string ClientsPage_NoCode {
            get {
                return ResourceManager.GetString("ClientsPage_NoCode", resourceCulture);
            }
        }

        public static string ClientsPage_OpenFoldersError {
            get {
                return ResourceManager.GetString("ClientsPage_OpenFoldersError", resourceCulture);
            }
        }

        public static string ClientsPage_OpeningFolder {
            get {
                return ResourceManager.GetString("ClientsPage_OpeningFolder", resourceCulture);
            }
        }

        public static string ClientsPage_OpeningFolders {
            get {
                return ResourceManager.GetString("ClientsPage_OpeningFolders", resourceCulture);
            }
        }

        public static string ClientsPage_QfileError {
            get {
                return ResourceManager.GetString("ClientsPage_QfileError", resourceCulture);
            }
        }

        public static string ClientsPage_SalespersonCreated {
            get {
                return ResourceManager.GetString("ClientsPage_SalespersonCreated", resourceCulture);
            }
        }

        public static string ClientsPage_SelectSalesperson {
            get {
                return ResourceManager.GetString("ClientsPage_SelectSalesperson", resourceCulture);
            }
        }

        public static string ClientsPage_ServicesToast {
            get {
                return ResourceManager.GetString("ClientsPage_ServicesToast", resourceCulture);
            }
        }

        public static string ClientsPage_UpdatedSuccess {
            get {
                return ResourceManager.GetString("ClientsPage_UpdatedSuccess", resourceCulture);
            }
        }

        public static string Common_Add {
            get {
                return ResourceManager.GetString("Common_Add", resourceCulture);
            }
        }

        public static string Common_Clear {
            get {
                return ResourceManager.GetString("Common_Clear", resourceCulture);
            }
        }

        public static string Common_Client {
            get {
                return ResourceManager.GetString("Common_Client", resourceCulture);
            }
        }

        public static string Common_CollaboratorNamePlaceholder {
            get {
                return ResourceManager.GetString("Common_CollaboratorNamePlaceholder", resourceCulture);
            }
        }

        public static string Common_Color {
            get {
                return ResourceManager.GetString("Common_Color", resourceCulture);
            }
        }

        public static string Common_Copy {
            get {
                return ResourceManager.GetString("Common_Copy", resourceCulture);
            }
        }

        public static string Common_CostCenter {
            get {
                return ResourceManager.GetString("Common_CostCenter", resourceCulture);
            }
        }

        public static string Common_CurrencyPlaceholder {
            get {
                return ResourceManager.GetString("Common_CurrencyPlaceholder", resourceCulture);
            }
        }

        public static string Common_Database {
            get {
                return ResourceManager.GetString("Common_Database", resourceCulture);
            }
        }

        public static string Common_Date {
            get {
                return ResourceManager.GetString("Common_Date", resourceCulture);
            }
        }

        public static string Common_DeleteError {
            get {
                return ResourceManager.GetString("Common_DeleteError", resourceCulture);
            }
        }

        public static string Common_DialCode {
            get {
                return ResourceManager.GetString("Common_DialCode", resourceCulture);
            }
        }

        public static string Common_Done {
            get {
                return ResourceManager.GetString("Common_Done", resourceCulture);
            }
        }

        public static string Common_ErrorOpeningPopup {
            get {
                return ResourceManager.GetString("Common_ErrorOpeningPopup", resourceCulture);
            }
        }

        public static string Common_ErrorTitle {
            get {
                return ResourceManager.GetString("Common_ErrorTitle", resourceCulture);
            }
        }

        public static string Common_Extras {
            get {
                return ResourceManager.GetString("Common_Extras", resourceCulture);
            }
        }

        public static string Common_Folders {
            get {
                return ResourceManager.GetString("Common_Folders", resourceCulture);
            }
        }

        public static string Common_Fri {
            get {
                return ResourceManager.GetString("Common_Fri", resourceCulture);
            }
        }

        public static string Common_Hours {
            get {
                return ResourceManager.GetString("Common_Hours", resourceCulture);
            }
        }

        public static string Common_HoursOld {
            get {
                return ResourceManager.GetString("Common_HoursOld", resourceCulture);
            }
        }

        public static string Common_Info {
            get {
                return ResourceManager.GetString("Common_Info", resourceCulture);
            }
        }

        public static string Common_Load {
            get {
                return ResourceManager.GetString("Common_Load", resourceCulture);
            }
        }

        public static string Common_Mon {
            get {
                return ResourceManager.GetString("Common_Mon", resourceCulture);
            }
        }

        public static string Common_Month {
            get {
                return ResourceManager.GetString("Common_Month", resourceCulture);
            }
        }

        public static string Common_NameLabel {
            get {
                return ResourceManager.GetString("Common_NameLabel", resourceCulture);
            }
        }

        public static string Common_New {
            get {
                return ResourceManager.GetString("Common_New", resourceCulture);
            }
        }

        public static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }

        public static string Common_Observations {
            get {
                return ResourceManager.GetString("Common_Observations", resourceCulture);
            }
        }

        public static string Common_Optional {
            get {
                return ResourceManager.GetString("Common_Optional", resourceCulture);
            }
        }

        public static string Common_Password {
            get {
                return ResourceManager.GetString("Common_Password", resourceCulture);
            }
        }

        public static string Common_Paste {
            get {
                return ResourceManager.GetString("Common_Paste", resourceCulture);
            }
        }

        public static string Common_PlaceholderWriteHere {
            get {
                return ResourceManager.GetString("Common_PlaceholderWriteHere", resourceCulture);
            }
        }

        public static string Common_Port {
            get {
                return ResourceManager.GetString("Common_Port", resourceCulture);
            }
        }

        public static string Common_RecordsCount {
            get {
                return ResourceManager.GetString("Common_RecordsCount", resourceCulture);
            }
        }

        public static string Common_Sat {
            get {
                return ResourceManager.GetString("Common_Sat", resourceCulture);
            }
        }

        public static string Common_SaveError {
            get {
                return ResourceManager.GetString("Common_SaveError", resourceCulture);
            }
        }

        public static string Common_SelectCollaborator {
            get {
                return ResourceManager.GetString("Common_SelectCollaborator", resourceCulture);
            }
        }

        public static string Common_SelectMonth {
            get {
                return ResourceManager.GetString("Common_SelectMonth", resourceCulture);
            }
        }

        public static string Common_Server {
            get {
                return ResourceManager.GetString("Common_Server", resourceCulture);
            }
        }

        public static string Common_Services {
            get {
                return ResourceManager.GetString("Common_Services", resourceCulture);
            }
        }

        public static string Common_Sun {
            get {
                return ResourceManager.GetString("Common_Sun", resourceCulture);
            }
        }

        public static string Common_Tags {
            get {
                return ResourceManager.GetString("Common_Tags", resourceCulture);
            }
        }

        public static string Common_Tasks {
            get {
                return ResourceManager.GetString("Common_Tasks", resourceCulture);
            }
        }

        public static string Common_Thu {
            get {
                return ResourceManager.GetString("Common_Thu", resourceCulture);
            }
        }

        public static string Common_Title {
            get {
                return ResourceManager.GetString("Common_Title", resourceCulture);
            }
        }

        public static string Common_Tue {
            get {
                return ResourceManager.GetString("Common_Tue", resourceCulture);
            }
        }

        public static string Common_User {
            get {
                return ResourceManager.GetString("Common_User", resourceCulture);
            }
        }

        public static string Common_Warning {
            get {
                return ResourceManager.GetString("Common_Warning", resourceCulture);
            }
        }

        public static string Common_Wed {
            get {
                return ResourceManager.GetString("Common_Wed", resourceCulture);
            }
        }

        public static string Common_Year {
            get {
                return ResourceManager.GetString("Common_Year", resourceCulture);
            }
        }

        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }

        public static string DbConfigPage_ConnectionError {
            get {
                return ResourceManager.GetString("DbConfigPage_ConnectionError", resourceCulture);
            }
        }

        public static string DbConfigPage_ConnectionErrorToast {
            get {
                return ResourceManager.GetString("DbConfigPage_ConnectionErrorToast", resourceCulture);
            }
        }

        public static string DbConfigPage_ConnectionOK {
            get {
                return ResourceManager.GetString("DbConfigPage_ConnectionOK", resourceCulture);
            }
        }

        public static string DbConfigPage_ConnectionSuccess {
            get {
                return ResourceManager.GetString("DbConfigPage_ConnectionSuccess", resourceCulture);
            }
        }

        public static string DbConfigPage_ConnectionSuccessToast {
            get {
                return ResourceManager.GetString("DbConfigPage_ConnectionSuccessToast", resourceCulture);
            }
        }

        public static string DbConfigPage_ContactEmail {
            get {
                return ResourceManager.GetString("DbConfigPage_ContactEmail", resourceCulture);
            }
        }

        public static string DbConfigPage_ContactEmailOptional {
            get {
                return ResourceManager.GetString("DbConfigPage_ContactEmailOptional", resourceCulture);
            }
        }

        public static string DbConfigPage_Diagnostic {
            get {
                return ResourceManager.GetString("DbConfigPage_Diagnostic", resourceCulture);
            }
        }

        public static string DbConfigPage_ErrorDatabase {
            get {
                return ResourceManager.GetString("DbConfigPage_ErrorDatabase", resourceCulture);
            }
        }

        public static string DbConfigPage_ErrorEmail {
            get {
                return ResourceManager.GetString("DbConfigPage_ErrorEmail", resourceCulture);
            }
        }

        public static string DbConfigPage_ErrorPassword {
            get {
                return ResourceManager.GetString("DbConfigPage_ErrorPassword", resourceCulture);
            }
        }

        public static string DbConfigPage_ErrorPort {
            get {
                return ResourceManager.GetString("DbConfigPage_ErrorPort", resourceCulture);
            }
        }

        public static string DbConfigPage_ErrorPrefix {
            get {
                return ResourceManager.GetString("DbConfigPage_ErrorPrefix", resourceCulture);
            }
        }

        public static string DbConfigPage_ErrorServer {
            get {
                return ResourceManager.GetString("DbConfigPage_ErrorServer", resourceCulture);
            }
        }

        public static string DbConfigPage_ErrorUser {
            get {
                return ResourceManager.GetString("DbConfigPage_ErrorUser", resourceCulture);
            }
        }

        public static string DbConfigPage_Failed {
            get {
                return ResourceManager.GetString("DbConfigPage_Failed", resourceCulture);
            }
        }

        public static string DbConfigPage_FixErrors {
            get {
                return ResourceManager.GetString("DbConfigPage_FixErrors", resourceCulture);
            }
        }

        public static string DbConfigPage_Header {
            get {
                return ResourceManager.GetString("DbConfigPage_Header", resourceCulture);
            }
        }

        public static string DbConfigPage_NoEndpoint {
            get {
                return ResourceManager.GetString("DbConfigPage_NoEndpoint", resourceCulture);
            }
        }

        public static string DbConfigPage_PrimaryOK {
            get {
                return ResourceManager.GetString("DbConfigPage_PrimaryOK", resourceCulture);
            }
        }

        public static string DbConfigPage_SaveAndTest {
            get {
                return ResourceManager.GetString("DbConfigPage_SaveAndTest", resourceCulture);
            }
        }

        public static string DbConfigPage_TestConnection {
            get {
                return ResourceManager.GetString("DbConfigPage_TestConnection", resourceCulture);
            }
        }

        public static string DbConfigPage_TestingConnection {
            get {
                return ResourceManager.GetString("DbConfigPage_TestingConnection", resourceCulture);
            }
        }

        public static string DbConfigPage_TestingMulti {
            get {
                return ResourceManager.GetString("DbConfigPage_TestingMulti", resourceCulture);
            }
        }

        public static string DbConfigPage_Title {
            get {
                return ResourceManager.GetString("DbConfigPage_Title", resourceCulture);
            }
        }

        public static string HorasColaboradorPage_AbsenceTypes {
            get {
                return ResourceManager.GetString("HorasColaboradorPage_AbsenceTypes", resourceCulture);
            }
        }

        public static string HorasColaboradorPage_AddHours {
            get {
                return ResourceManager.GetString("HorasColaboradorPage_AddHours", resourceCulture);
            }
        }

        public static string HorasColaboradorPage_Calendar {
            get {
                return ResourceManager.GetString("HorasColaboradorPage_Calendar", resourceCulture);
            }
        }

        public static string HorasColaboradorPage_Collaborator {
            get {
                return ResourceManager.GetString("HorasColaboradorPage_Collaborator", resourceCulture);
            }
        }

        public static string HorasColaboradorPage_DayDetails {
            get {
                return ResourceManager.GetString("HorasColaboradorPage_DayDetails", resourceCulture);
            }
        }

        public static string HorasColaboradorPage_Extra {
            get {
                return ResourceManager.GetString("HorasColaboradorPage_Extra", resourceCulture);
            }
        }

        public static string HorasColaboradorPage_Last30Days {
            get {
                return ResourceManager.GetString("HorasColaboradorPage_Last30Days", resourceCulture);
            }
        }

        public static string HorasColaboradorPage_List {
            get {
                return ResourceManager.GetString("HorasColaboradorPage_List", resourceCulture);
            }
        }

        public static string HorasColaboradorPage_MonthCalendar {
            get {
                return ResourceManager.GetString("HorasColaboradorPage_MonthCalendar", resourceCulture);
            }
        }

        public static string HorasColaboradorPage_NoRecords {
            get {
                return ResourceManager.GetString("HorasColaboradorPage_NoRecords", resourceCulture);
            }
        }

        public static string HorasColaboradorPage_Normal {
            get {
                return ResourceManager.GetString("HorasColaboradorPage_Normal", resourceCulture);
            }
        }

        public static string HorasColaboradorPage_Period {
            get {
                return ResourceManager.GetString("HorasColaboradorPage_Period", resourceCulture);
            }
        }

        public static string HorasColaboradorPage_PopupError {
            get {
                return ResourceManager.GetString("HorasColaboradorPage_PopupError", resourceCulture);
            }
        }

        public static string HorasColaboradorPage_SelectCollaborator {
            get {
                return ResourceManager.GetString("HorasColaboradorPage_SelectCollaborator", resourceCulture);
            }
        }

        public static string HorasColaboradorPage_SelectPeriod {
            get {
                return ResourceManager.GetString("HorasColaboradorPage_SelectPeriod", resourceCulture);
            }
        }

        public static string HorasColaboradorPage_Summary {
            get {
                return ResourceManager.GetString("HorasColaboradorPage_Summary", resourceCulture);
            }
        }

        public static string HorasColaboradorPage_ThisMonth {
            get {
                return ResourceManager.GetString("HorasColaboradorPage_ThisMonth", resourceCulture);
            }
        }

        public static string HorasColaboradorPage_ThisWeek {
            get {
                return ResourceManager.GetString("HorasColaboradorPage_ThisWeek", resourceCulture);
            }
        }

        public static string HorasColaboradorPage_Title {
            get {
                return ResourceManager.GetString("HorasColaboradorPage_Title", resourceCulture);
            }
        }

        public static string HorasColaboradorPage_Today {
            get {
                return ResourceManager.GetString("HorasColaboradorPage_Today", resourceCulture);
            }
        }

        public static string HoursEntryPage_DeleteMonth {
            get {
                return ResourceManager.GetString("HoursEntryPage_DeleteMonth", resourceCulture);
            }
        }

        public static string HoursEntryPage_EditNotesMessage {
            get {
                return ResourceManager.GetString("HoursEntryPage_EditNotesMessage", resourceCulture);
            }
        }

        public static string HoursEntryPage_ExportMonth {
            get {
                return ResourceManager.GetString("HoursEntryPage_ExportMonth", resourceCulture);
            }
        }

        public static string HoursEntryPage_ExportYear {
            get {
                return ResourceManager.GetString("HoursEntryPage_ExportYear", resourceCulture);
            }
        }

        public static string HoursEntryPage_HeaderPlusMinus {
            get {
                return ResourceManager.GetString("HoursEntryPage_HeaderPlusMinus", resourceCulture);
            }
        }

        public static string HoursEntryPage_HeaderSel {
            get {
                return ResourceManager.GetString("HoursEntryPage_HeaderSel", resourceCulture);
            }
        }

        public static string HoursEntryPage_HourRate {
            get {
                return ResourceManager.GetString("HoursEntryPage_HourRate", resourceCulture);
            }
        }

        public static string HoursEntryPage_MonthTotals {
            get {
                return ResourceManager.GetString("HoursEntryPage_MonthTotals", resourceCulture);
            }
        }

        public static string HoursEntryPage_Title {
            get {
                return ResourceManager.GetString("HoursEntryPage_Title", resourceCulture);
            }
        }

        public static string Login_Config {
            get {
                return ResourceManager.GetString("Login_Config", resourceCulture);
            }
        }

        public static string Login_EmailPlaceholder {
            get {
                return ResourceManager.GetString("Login_EmailPlaceholder", resourceCulture);
            }
        }

        public static string Login_Error_EmailFail {
            get {
                return ResourceManager.GetString("Login_Error_EmailFail", resourceCulture);
            }
        }

        public static string Login_Error_ResetFail {
            get {
                return ResourceManager.GetString("Login_Error_ResetFail", resourceCulture);
            }
        }

        public static string Login_InternalReset_Fail {
            get {
                return ResourceManager.GetString("Login_InternalReset_Fail", resourceCulture);
            }
        }

        public static string Login_InternalReset_InvalidKey {
            get {
                return ResourceManager.GetString("Login_InternalReset_InvalidKey", resourceCulture);
            }
        }

        public static string Login_InternalReset_KeyPlaceholder {
            get {
                return ResourceManager.GetString("Login_InternalReset_KeyPlaceholder", resourceCulture);
            }
        }

        public static string Login_InternalReset_KeyPrompt {
            get {
                return ResourceManager.GetString("Login_InternalReset_KeyPrompt", resourceCulture);
            }
        }

        public static string Login_InternalReset_Success {
            get {
                return ResourceManager.GetString("Login_InternalReset_Success", resourceCulture);
            }
        }

        public static string Login_InternalReset_Title {
            get {
                return ResourceManager.GetString("Login_InternalReset_Title", resourceCulture);
            }
        }

        public static string Login_Msg_EnterUserAndPass {
            get {
                return ResourceManager.GetString("Login_Msg_EnterUserAndPass", resourceCulture);
            }
        }

        public static string Login_Msg_InvalidCredentials {
            get {
                return ResourceManager.GetString("Login_Msg_InvalidCredentials", resourceCulture);
            }
        }

        public static string Login_Msg_LoginError {
            get {
                return ResourceManager.GetString("Login_Msg_LoginError", resourceCulture);
            }
        }

        public static string Login_PasswordMaskPlaceholder {
            get {
                return ResourceManager.GetString("Login_PasswordMaskPlaceholder", resourceCulture);
            }
        }

        public static string Login_Recovery_CodePlaceholder {
            get {
                return ResourceManager.GetString("Login_Recovery_CodePlaceholder", resourceCulture);
            }
        }

        public static string Login_Recovery_EmailCodeMsg {
            get {
                return ResourceManager.GetString("Login_Recovery_EmailCodeMsg", resourceCulture);
            }
        }

        public static string Login_Recovery_EmailCodeTitle {
            get {
                return ResourceManager.GetString("Login_Recovery_EmailCodeTitle", resourceCulture);
            }
        }

        public static string Login_Recovery_EmailSent {
            get {
                return ResourceManager.GetString("Login_Recovery_EmailSent", resourceCulture);
            }
        }

        public static string Login_Recovery_EnterUserFirst {
            get {
                return ResourceManager.GetString("Login_Recovery_EnterUserFirst", resourceCulture);
            }
        }

        public static string Login_Recovery_InvalidCode {
            get {
                return ResourceManager.GetString("Login_Recovery_InvalidCode", resourceCulture);
            }
        }

        public static string Login_Recovery_NewPassMsg {
            get {
                return ResourceManager.GetString("Login_Recovery_NewPassMsg", resourceCulture);
            }
        }

        public static string Login_Recovery_NewPassTitle {
            get {
                return ResourceManager.GetString("Login_Recovery_NewPassTitle", resourceCulture);
            }
        }

        public static string Login_Recovery_NoEmail {
            get {
                return ResourceManager.GetString("Login_Recovery_NoEmail", resourceCulture);
            }
        }

        public static string Login_Recovery_Success {
            get {
                return ResourceManager.GetString("Login_Recovery_Success", resourceCulture);
            }
        }

        public static string Login_Recovery_Title {
            get {
                return ResourceManager.GetString("Login_Recovery_Title", resourceCulture);
            }
        }

        public static string Login_SearchingUser {
            get {
                return ResourceManager.GetString("Login_SearchingUser", resourceCulture);
            }
        }

        public static string Login_UserNotFound {
            get {
                return ResourceManager.GetString("Login_UserNotFound", resourceCulture);
            }
        }

        public static string Login_Validation_EnterPass {
            get {
                return ResourceManager.GetString("Login_Validation_EnterPass", resourceCulture);
            }
        }

        public static string Login_Validation_MinChars {
            get {
                return ResourceManager.GetString("Login_Validation_MinChars", resourceCulture);
            }
        }

        public static string Login_Validation_Title {
            get {
                return ResourceManager.GetString("Login_Validation_Title", resourceCulture);
            }
        }

        public static string Login_WelcomeSimple {
            get {
                return ResourceManager.GetString("Login_WelcomeSimple", resourceCulture);
            }
        }

        public static string Login_WelcomeUser {
            get {
                return ResourceManager.GetString("Login_WelcomeUser", resourceCulture);
            }
        }

        public static string MainPage_AdminAccess {
            get {
                return ResourceManager.GetString("MainPage_AdminAccess", resourceCulture);
            }
        }

        public static string MainPage_Dashboard {
            get {
                return ResourceManager.GetString("MainPage_Dashboard", resourceCulture);
            }
        }

        public static string MainPage_DbConnection {
            get {
                return ResourceManager.GetString("MainPage_DbConnection", resourceCulture);
            }
        }

        public static string MainPage_Swipe {
            get {
                return ResourceManager.GetString("MainPage_Swipe", resourceCulture);
            }
        }

        public static string MainPage_Theme {
            get {
                return ResourceManager.GetString("MainPage_Theme", resourceCulture);
            }
        }

        public static string MainPage_ThemeAuto {
            get {
                return ResourceManager.GetString("MainPage_ThemeAuto", resourceCulture);
            }
        }

        public static string MainPage_ThemeDark {
            get {
                return ResourceManager.GetString("MainPage_ThemeDark", resourceCulture);
            }
        }

        public static string MainPage_ThemeLight {
            get {
                return ResourceManager.GetString("MainPage_ThemeLight", resourceCulture);
            }
        }

        public static string MainPage_Users {
            get {
                return ResourceManager.GetString("MainPage_Users", resourceCulture);
            }
        }

        public static string MainPage_WelcomeTo {
            get {
                return ResourceManager.GetString("MainPage_WelcomeTo", resourceCulture);
            }
        }

        public static string Main_PageNoContent {
            get {
                return ResourceManager.GetString("Main_PageNoContent", resourceCulture);
            }
        }

        public static string ManageMetaPage_Categories {
            get {
                return ResourceManager.GetString("ManageMetaPage_Categories", resourceCulture);
            }
        }

        public static string ManageMetaPage_ColorHint {
            get {
                return ResourceManager.GetString("ManageMetaPage_ColorHint", resourceCulture);
            }
        }

        public static string ManageMetaPage_ResetApp {
            get {
                return ResourceManager.GetString("ManageMetaPage_ResetApp", resourceCulture);
            }
        }

        public static string ManageMetaPage_Tags {
            get {
                return ResourceManager.GetString("ManageMetaPage_Tags", resourceCulture);
            }
        }

        public static string ManageMetaPage_Title {
            get {
                return ResourceManager.GetString("ManageMetaPage_Title", resourceCulture);
            }
        }

        public static string ProductsPage_DeleteMessage {
            get {
                return ResourceManager.GetString("ProductsPage_DeleteMessage", resourceCulture);
            }
        }

        public static string ProductsPage_DeleteProduct {
            get {
                return ResourceManager.GetString("ProductsPage_DeleteProduct", resourceCulture);
            }
        }

        public static string ProductsPage_DeleteTitle {
            get {
                return ResourceManager.GetString("ProductsPage_DeleteTitle", resourceCulture);
            }
        }

        public static string ProductsPage_EditProduct {
            get {
                return ResourceManager.GetString("ProductsPage_EditProduct", resourceCulture);
            }
        }

        public static string ProductsPage_LoadError {
            get {
                return ResourceManager.GetString("ProductsPage_LoadError", resourceCulture);
            }
        }

        public static string ProductsPage_ProductUnidentified {
            get {
                return ResourceManager.GetString("ProductsPage_ProductUnidentified", resourceCulture);
            }
        }

        public static string ProjectDetailPage_Category {
            get {
                return ResourceManager.GetString("ProjectDetailPage_Category", resourceCulture);
            }
        }

        public static string ProjectDetailPage_Delete {
            get {
                return ResourceManager.GetString("ProjectDetailPage_Delete", resourceCulture);
            }
        }

        public static string ProjectDetailPage_Description {
            get {
                return ResourceManager.GetString("ProjectDetailPage_Description", resourceCulture);
            }
        }

        public static string ProjectDetailPage_Icon {
            get {
                return ResourceManager.GetString("ProjectDetailPage_Icon", resourceCulture);
            }
        }

        public static string ProjectDetailPage_IconHint {
            get {
                return ResourceManager.GetString("ProjectDetailPage_IconHint", resourceCulture);
            }
        }

        public static string ProjectDetailPage_Name {
            get {
                return ResourceManager.GetString("ProjectDetailPage_Name", resourceCulture);
            }
        }

        public static string ProjectDetailPage_Title {
            get {
                return ResourceManager.GetString("ProjectDetailPage_Title", resourceCulture);
            }
        }

        public static string ProjectListPage_Title {
            get {
                return ResourceManager.GetString("ProjectListPage_Title", resourceCulture);
            }
        }

        public static string RegisterPage_Category1 {
            get {
                return ResourceManager.GetString("RegisterPage_Category1", resourceCulture);
            }
        }

        public static string RegisterPage_Category2 {
            get {
                return ResourceManager.GetString("RegisterPage_Category2", resourceCulture);
            }
        }

        public static string RegisterPage_ChangePhoto {
            get {
                return ResourceManager.GetString("RegisterPage_ChangePhoto", resourceCulture);
            }
        }

        public static string RegisterPage_Close {
            get {
                return ResourceManager.GetString("RegisterPage_Close", resourceCulture);
            }
        }

        public static string RegisterPage_Contact {
            get {
                return ResourceManager.GetString("RegisterPage_Contact", resourceCulture);
            }
        }

        public static string RegisterPage_ContactPlaceholder {
            get {
                return ResourceManager.GetString("RegisterPage_ContactPlaceholder", resourceCulture);
            }
        }

        public static string RegisterPage_DeleteConfirmMessage {
            get {
                return ResourceManager.GetString("RegisterPage_DeleteConfirmMessage", resourceCulture);
            }
        }

        public static string RegisterPage_DeleteConfirmTitle {
            get {
                return ResourceManager.GetString("RegisterPage_DeleteConfirmTitle", resourceCulture);
            }
        }

        public static string RegisterPage_Email {
            get {
                return ResourceManager.GetString("RegisterPage_Email", resourceCulture);
            }
        }

        public static string RegisterPage_EmailPlaceholder {
            get {
                return ResourceManager.GetString("RegisterPage_EmailPlaceholder", resourceCulture);
            }
        }

        public static string RegisterPage_Error_Category1Required {
            get {
                return ResourceManager.GetString("RegisterPage_Error_Category1Required", resourceCulture);
            }
        }

        public static string RegisterPage_Error_Category2Required {
            get {
                return ResourceManager.GetString("RegisterPage_Error_Category2Required", resourceCulture);
            }
        }

        public static string RegisterPage_Error_ContactRequired {
            get {
                return ResourceManager.GetString("RegisterPage_Error_ContactRequired", resourceCulture);
            }
        }

        public static string RegisterPage_Error_DeleteUsername {
            get {
                return ResourceManager.GetString("RegisterPage_Error_DeleteUsername", resourceCulture);
            }
        }

        public static string RegisterPage_Error_EmailInvalid {
            get {
                return ResourceManager.GetString("RegisterPage_Error_EmailInvalid", resourceCulture);
            }
        }

        public static string RegisterPage_Error_FillRequired {
            get {
                return ResourceManager.GetString("RegisterPage_Error_FillRequired", resourceCulture);
            }
        }

        public static string RegisterPage_Error_NameRequired {
            get {
                return ResourceManager.GetString("RegisterPage_Error_NameRequired", resourceCulture);
            }
        }

        public static string RegisterPage_Error_PasswordRequired {
            get {
                return ResourceManager.GetString("RegisterPage_Error_PasswordRequired", resourceCulture);
            }
        }

        public static string RegisterPage_Error_TypeRequired {
            get {
                return ResourceManager.GetString("RegisterPage_Error_TypeRequired", resourceCulture);
            }
        }

        public static string RegisterPage_Error_UserExists {
            get {
                return ResourceManager.GetString("RegisterPage_Error_UserExists", resourceCulture);
            }
        }

        public static string RegisterPage_Error_UsernameRequired {
            get {
                return ResourceManager.GetString("RegisterPage_Error_UsernameRequired", resourceCulture);
            }
        }

        public static string RegisterPage_FullName {
            get {
                return ResourceManager.GetString("RegisterPage_FullName", resourceCulture);
            }
        }

        public static string RegisterPage_ImageError {
            get {
                return ResourceManager.GetString("RegisterPage_ImageError", resourceCulture);
            }
        }

        public static string RegisterPage_ImageTooLarge {
            get {
                return ResourceManager.GetString("RegisterPage_ImageTooLarge", resourceCulture);
            }
        }

        public static string RegisterPage_List {
            get {
                return ResourceManager.GetString("RegisterPage_List", resourceCulture);
            }
        }

        public static string RegisterPage_ListUpdated {
            get {
                return ResourceManager.GetString("RegisterPage_ListUpdated", resourceCulture);
            }
        }

        public static string RegisterPage_LoadError {
            get {
                return ResourceManager.GetString("RegisterPage_LoadError", resourceCulture);
            }
        }

        public static string RegisterPage_NamePlaceholder {
            get {
                return ResourceManager.GetString("RegisterPage_NamePlaceholder", resourceCulture);
            }
        }

        public static string RegisterPage_New {
            get {
                return ResourceManager.GetString("RegisterPage_New", resourceCulture);
            }
        }

        public static string RegisterPage_NoChanges {
            get {
                return ResourceManager.GetString("RegisterPage_NoChanges", resourceCulture);
            }
        }

        public static string RegisterPage_Password {
            get {
                return ResourceManager.GetString("RegisterPage_Password", resourceCulture);
            }
        }

        public static string RegisterPage_PickImageTitle {
            get {
                return ResourceManager.GetString("RegisterPage_PickImageTitle", resourceCulture);
            }
        }

        public static string RegisterPage_SelectUser {
            get {
                return ResourceManager.GetString("RegisterPage_SelectUser", resourceCulture);
            }
        }

        public static string RegisterPage_Title {
            get {
                return ResourceManager.GetString("RegisterPage_Title", resourceCulture);
            }
        }

        public static string RegisterPage_UserDeleteFail {
            get {
                return ResourceManager.GetString("RegisterPage_UserDeleteFail", resourceCulture);
            }
        }

        public static string RegisterPage_UserDeleted {
            get {
                return ResourceManager.GetString("RegisterPage_UserDeleted", resourceCulture);
            }
        }

        public static string RegisterPage_UserList {
            get {
                return ResourceManager.GetString("RegisterPage_UserList", resourceCulture);
            }
        }

        public static string RegisterPage_UserPlaceholder {
            get {
                return ResourceManager.GetString("RegisterPage_UserPlaceholder", resourceCulture);
            }
        }

        public static string RegisterPage_UserSaved {
            get {
                return ResourceManager.GetString("RegisterPage_UserSaved", resourceCulture);
            }
        }

        public static string RegisterPage_UserType {
            get {
                return ResourceManager.GetString("RegisterPage_UserType", resourceCulture);
            }
        }

        public static string RegisterPage_UserTypePlaceholder {
            get {
                return ResourceManager.GetString("RegisterPage_UserTypePlaceholder", resourceCulture);
            }
        }

        public static string RegisterPage_UserUpdated {
            get {
                return ResourceManager.GetString("RegisterPage_UserUpdated", resourceCulture);
            }
        }

        public static string RegisterPage_Username {
            get {
                return ResourceManager.GetString("RegisterPage_Username", resourceCulture);
            }
        }

        public static string ServicePage_ErrorBinding {
            get {
                return ResourceManager.GetString("ServicePage_ErrorBinding", resourceCulture);
            }
        }

        public static string ServicePage_LoadFailure {
            get {
                return ResourceManager.GetString("ServicePage_LoadFailure", resourceCulture);
            }
        }

        public static string ServicePage_SearchPlaceholder {
            get {
                return ResourceManager.GetString("ServicePage_SearchPlaceholder", resourceCulture);
            }
        }

        public static string ServicePage_ZeroLoaded {
            get {
                return ResourceManager.GetString("ServicePage_ZeroLoaded", resourceCulture);
            }
        }

        public static string Splash_GifErrorMessage {
            get {
                return ResourceManager.GetString("Splash_GifErrorMessage", resourceCulture);
            }
        }

        public static string Splash_GifErrorTitle {
            get {
                return ResourceManager.GetString("Splash_GifErrorTitle", resourceCulture);
            }
        }

        public static string Splash_Version {
            get {
                return ResourceManager.GetString("Splash_Version", resourceCulture);
            }
        }

        public static string Splash_VersionPrefix {
            get {
                return ResourceManager.GetString("Splash_VersionPrefix", resourceCulture);
            }
        }

        public static string SwipeProofPage_Delete {
            get {
                return ResourceManager.GetString("SwipeProofPage_Delete", resourceCulture);
            }
        }

        public static string SwipeProofPage_DeleteConfirm {
            get {
                return ResourceManager.GetString("SwipeProofPage_DeleteConfirm", resourceCulture);
            }
        }

        public static string SwipeProofPage_Deleted {
            get {
                return ResourceManager.GetString("SwipeProofPage_Deleted", resourceCulture);
            }
        }

        public static string SwipeProofPage_Edit {
            get {
                return ResourceManager.GetString("SwipeProofPage_Edit", resourceCulture);
            }
        }

        public static string SwipeProofPage_EditMessage {
            get {
                return ResourceManager.GetString("SwipeProofPage_EditMessage", resourceCulture);
            }
        }

        public static string SwipeProofPage_EditTitle {
            get {
                return ResourceManager.GetString("SwipeProofPage_EditTitle", resourceCulture);
            }
        }

        public static string SwipeProofPage_Folders {
            get {
                return ResourceManager.GetString("SwipeProofPage_Folders", resourceCulture);
            }
        }

        public static string SwipeProofPage_QfileError {
            get {
                return ResourceManager.GetString("SwipeProofPage_QfileError", resourceCulture);
            }
        }

        public static string SwipeProofPage_Title {
            get {
                return ResourceManager.GetString("SwipeProofPage_Title", resourceCulture);
            }
        }

        public static string TaskDetailPage_Completed {
            get {
                return ResourceManager.GetString("TaskDetailPage_Completed", resourceCulture);
            }
        }

        public static string TaskDetailPage_CompletedHint {
            get {
                return ResourceManager.GetString("TaskDetailPage_CompletedHint", resourceCulture);
            }
        }

        public static string TaskDetailPage_Project {
            get {
                return ResourceManager.GetString("TaskDetailPage_Project", resourceCulture);
            }
        }

        public static string TaskDetailPage_ProjectHint {
            get {
                return ResourceManager.GetString("TaskDetailPage_ProjectHint", resourceCulture);
            }
        }

        public static string TaskDetailPage_Status {
            get {
                return ResourceManager.GetString("TaskDetailPage_Status", resourceCulture);
            }
        }

        public static string TaskDetailPage_Task {
            get {
                return ResourceManager.GetString("TaskDetailPage_Task", resourceCulture);
            }
        }

        public static string TaskDetailPage_Title {
            get {
                return ResourceManager.GetString("TaskDetailPage_Title", resourceCulture);
            }
        }

        public static string Update_ButtonExit {
            get {
                return ResourceManager.GetString("Update_ButtonExit", resourceCulture);
            }
        }

        public static string Update_ButtonLater {
            get {
                return ResourceManager.GetString("Update_ButtonLater", resourceCulture);
            }
        }

        public static string Update_ButtonUpdate {
            get {
                return ResourceManager.GetString("Update_ButtonUpdate", resourceCulture);
            }
        }

        public static string Update_ButtonUpdateNow {
            get {
                return ResourceManager.GetString("Update_ButtonUpdateNow", resourceCulture);
            }
        }

        public static string Update_CheckNotes {
            get {
                return ResourceManager.GetString("Update_CheckNotes", resourceCulture);
            }
        }

        public static string Update_MandatoryHeader {
            get {
                return ResourceManager.GetString("Update_MandatoryHeader", resourceCulture);
            }
        }

        public static string Update_NewVersionAvailable {
            get {
                return ResourceManager.GetString("Update_NewVersionAvailable", resourceCulture);
            }
        }

        public static string Update_TitleAvailable {
            get {
                return ResourceManager.GetString("Update_TitleAvailable", resourceCulture);
            }
        }

        public static string Update_TitleMandatory {
            get {
                return ResourceManager.GetString("Update_TitleMandatory", resourceCulture);
            }
        }

        public static string WelcomePage_ChooseCompany {
            get {
                return ResourceManager.GetString("WelcomePage_ChooseCompany", resourceCulture);
            }
        }

        public static string WelcomePage_Connecting {
            get {
                return ResourceManager.GetString("WelcomePage_Connecting", resourceCulture);
            }
        }

        public static string WelcomePage_ConnectionFailed {
            get {
                return ResourceManager.GetString("WelcomePage_ConnectionFailed", resourceCulture);
            }
        }

        public static string WelcomePage_ConnectionFailedConfig {
            get {
                return ResourceManager.GetString("WelcomePage_ConnectionFailedConfig", resourceCulture);
            }
        }

        public static string WelcomePage_Loading {
            get {
                return ResourceManager.GetString("WelcomePage_Loading", resourceCulture);
            }
        }

        public static string WelcomePage_LoginNavError {
            get {
                return ResourceManager.GetString("WelcomePage_LoginNavError", resourceCulture);
            }
        }

        public static string WelcomePage_NoActiveCompany {
            get {
                return ResourceManager.GetString("WelcomePage_NoActiveCompany", resourceCulture);
            }
        }

        public static string WelcomePage_WelcomeToCompany {
            get {
                return ResourceManager.GetString("WelcomePage_WelcomeToCompany", resourceCulture);
            }
        }

        public static string ProductsPage_EditFamily { get { return ResourceManager.GetString("ProductsPage_EditFamily", resourceCulture); } }
        public static string ProductsPage_FamilyDescriptionRequired { get { return ResourceManager.GetString("ProductsPage_FamilyDescriptionRequired", resourceCulture); } }
        public static string ProductsPage_FamilySaveError { get { return ResourceManager.GetString("ProductsPage_FamilySaveError", resourceCulture); } }
        public static string ProductsPage_FamilyUpdated { get { return ResourceManager.GetString("ProductsPage_FamilyUpdated", resourceCulture); } }
        public static string ProductsPage_FamilyDeleteError { get { return ResourceManager.GetString("ProductsPage_FamilyDeleteError", resourceCulture); } }
        public static string ProductsPage_FamilyDeleted { get { return ResourceManager.GetString("ProductsPage_FamilyDeleted", resourceCulture); } }
        public static string ProductsPage_FamilyCodeRequired { get { return ResourceManager.GetString("ProductsPage_FamilyCodeRequired", resourceCulture); } }
        public static string ProductsPage_FamilyCreated { get { return ResourceManager.GetString("ProductsPage_FamilyCreated", resourceCulture); } }
        public static string Hours_ErrorInvalidNormalHours { get { return ResourceManager.GetString("Hours_ErrorInvalidNormalHours", resourceCulture); } }
        public static string Hours_ErrorInvalidExtraHours { get { return ResourceManager.GetString("Hours_ErrorInvalidExtraHours", resourceCulture); } }
        public static string Hours_ErrorTotalHoursExceeded { get { return ResourceManager.GetString("Hours_ErrorTotalHoursExceeded", resourceCulture); } }
        public static string Common_Open { get { return ResourceManager.GetString("Common_Open", resourceCulture); } }
        public static string Common_Logs { get { return ResourceManager.GetString("Common_Logs", resourceCulture); } }
        public static string Common_Details { get { return ResourceManager.GetString("Common_Details", resourceCulture); } }
        public static string Common_Share { get { return ResourceManager.GetString("Common_Share", resourceCulture); } }
        public static string Common_Copied { get { return ResourceManager.GetString("Common_Copied", resourceCulture); } }
        public static string Common_DetailsCopied { get { return ResourceManager.GetString("Common_DetailsCopied", resourceCulture); } }
        public static string ProductsPage_FamilyFormError { get { return ResourceManager.GetString("ProductsPage_FamilyFormError", resourceCulture); } }
        public static string ProductsPage_FamilyFillRequired { get { return ResourceManager.GetString("ProductsPage_FamilyFillRequired", resourceCulture); } }
        public static string ProductsPage_FamilyLoadError { get { return ResourceManager.GetString("ProductsPage_FamilyLoadError", resourceCulture); } }
        public static string ClientsPage_SalespersonFormError { get { return ResourceManager.GetString("ClientsPage_SalespersonFormError", resourceCulture); } }
        public static string ClientsPage_SalespersonNameRequired { get { return ResourceManager.GetString("ClientsPage_SalespersonNameRequired", resourceCulture); } }
        public static string ClientsPage_SalespersonSaveError { get { return ResourceManager.GetString("ClientsPage_SalespersonSaveError", resourceCulture); } }
        public static string ClientsPage_SalespersonLoadError { get { return ResourceManager.GetString("ClientsPage_SalespersonLoadError", resourceCulture); } }

        public static string Common_Success { get { return ResourceManager.GetString("Common_Success", resourceCulture); } }
        public static string Pdf_FolderCreatedButNotFound { get { return ResourceManager.GetString("Pdf_FolderCreatedButNotFound", resourceCulture); } }
        public static string Pdf_FileExists { get { return ResourceManager.GetString("Pdf_FileExists", resourceCulture); } }
        public static string Pdf_FileExistsMessage { get { return ResourceManager.GetString("Pdf_FileExistsMessage", resourceCulture); } }
        public static string Pdf_SavedSuccess { get { return ResourceManager.GetString("Pdf_SavedSuccess", resourceCulture); } }
        public static string Pdf_GenerationError { get { return ResourceManager.GetString("Pdf_GenerationError", resourceCulture); } }
        public static string Pdf_SaveError { get { return ResourceManager.GetString("Pdf_SaveError", resourceCulture); } }
        public static string Pdf_ShareTitle { get { return ResourceManager.GetString("Pdf_ShareTitle", resourceCulture); } }
        public static string Pdf_ShareError { get { return ResourceManager.GetString("Pdf_ShareError", resourceCulture); } }
        public static string Pdf_FolderNotFound { get { return ResourceManager.GetString("Pdf_FolderNotFound", resourceCulture); } }
        public static string Pdf_FolderNotFoundMessage { get { return ResourceManager.GetString("Pdf_FolderNotFoundMessage", resourceCulture); } }
        public static string Print_Error { get { return ResourceManager.GetString("Print_Error", resourceCulture); } }
        public static string Print_ViewAccessError { get { return ResourceManager.GetString("Print_ViewAccessError", resourceCulture); } }
        public static string Print_StartError { get { return ResourceManager.GetString("Print_StartError", resourceCulture); } }
        public static string Products_LoadError { get { return ResourceManager.GetString("Products_LoadError", resourceCulture); } }

    }
}
