//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAVIGEST.macOS.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NAVIGEST.macOS.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ClientsPage_Title {
            get {
                return ResourceManager.GetString("ClientsPage_Title", resourceCulture);
            }
        }
        
        public static string ClientsPage_NewClient {
            get {
                return ResourceManager.GetString("ClientsPage_NewClient", resourceCulture);
            }
        }

        public static string ClientsPage_AddClient {
            get {
                return ResourceManager.GetString("ClientsPage_AddClient", resourceCulture);
            }
        }

        public static string ClientsPage_EditClient {
            get {
                return ResourceManager.GetString("ClientsPage_EditClient", resourceCulture);
            }
        }

        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }

        public static string Common_Update {
            get {
                return ResourceManager.GetString("Common_Update", resourceCulture);
            }
        }

        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }

        public static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }

        public static string Common_SearchPlaceholder {
            get {
                return ResourceManager.GetString("Common_SearchPlaceholder", resourceCulture);
            }
        }

        public static string Common_Name {
            get {
                return ResourceManager.GetString("Common_Name", resourceCulture);
            }
        }

        public static string Common_Code {
            get {
                return ResourceManager.GetString("Common_Code", resourceCulture);
            }
        }

        public static string Common_Phone {
            get {
                return ResourceManager.GetString("Common_Phone", resourceCulture);
            }
        }

        public static string Common_Email {
            get {
                return ResourceManager.GetString("Common_Email", resourceCulture);
            }
        }

        public static string ClientsPage_Salesperson {
            get {
                return ResourceManager.GetString("ClientsPage_Salesperson", resourceCulture);
            }
        }

        public static string ClientsPage_ClientNamePlaceholder {
            get {
                return ResourceManager.GetString("ClientsPage_ClientNamePlaceholder", resourceCulture);
            }
        }

        public static string ClientsPage_CreditValue {
            get {
                return ResourceManager.GetString("ClientsPage_CreditValue", resourceCulture);
            }
        }

        public static string ClientsPage_ExternalLabel {
            get {
                return ResourceManager.GetString("ClientsPage_ExternalLabel", resourceCulture);
            }
        }

        public static string ClientsPage_CancelledLabel {
            get {
                return ResourceManager.GetString("ClientsPage_CancelledLabel", resourceCulture);
            }
        }

        public static string ClientsPage_SyncedFolders {
            get {
                return ResourceManager.GetString("ClientsPage_SyncedFolders", resourceCulture);
            }
        }
        
        public static string ClientsPage_External {
             get {
                 return ResourceManager.GetString("ClientsPage_External", resourceCulture);
             }
        }

        public static string ClientsPage_Cancelled {
             get {
                 return ResourceManager.GetString("ClientsPage_Cancelled", resourceCulture);
             }
        }

        public static string ProductsPage_Title {
            get {
                return ResourceManager.GetString("ProductsPage_Title", resourceCulture);
            }
        }

        public static string ProductsPage_NewProduct {
            get {
                return ResourceManager.GetString("ProductsPage_NewProduct", resourceCulture);
            }
        }

        public static string ProductsPage_SearchPlaceholder {
            get {
                return ResourceManager.GetString("ProductsPage_SearchPlaceholder", resourceCulture);
            }
        }

        public static string Common_Cost {
            get {
                return ResourceManager.GetString("Common_Cost", resourceCulture);
            }
        }

        public static string Common_Sale {
            get {
                return ResourceManager.GetString("Common_Sale", resourceCulture);
            }
        }

        public static string Common_TotalSales {
            get {
                return ResourceManager.GetString("Common_TotalSales", resourceCulture);
            }
        }

        public static string Common_Collaborator {
            get {
                return ResourceManager.GetString("Common_Collaborator", resourceCulture);
            }
        }

        public static string Common_Description {
            get {
                return ResourceManager.GetString("Common_Description", resourceCulture);
            }
        }

        public static string Common_Family {
            get {
                return ResourceManager.GetString("Common_Family", resourceCulture);
            }
        }

        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }

        public static string Common_Search {
            get {
                return ResourceManager.GetString("Common_Search", resourceCulture);
            }
        }

        public static string ProductsPage_CostPrice {
            get {
                return ResourceManager.GetString("ProductsPage_CostPrice", resourceCulture);
            }
        }

        public static string ProductsPage_SalePrice {
            get {
                return ResourceManager.GetString("ProductsPage_SalePrice", resourceCulture);
            }
        }

        public static string ProductsPage_ProductDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("ProductsPage_ProductDescriptionPlaceholder", resourceCulture);
            }
        }

        public static string ProductsPage_SelectFamily {
            get {
                return ResourceManager.GetString("ProductsPage_SelectFamily", resourceCulture);
            }
        }

        public static string ProductsPage_AddFamily {
            get {
                return ResourceManager.GetString("ProductsPage_AddFamily", resourceCulture);
            }
        }

        public static string ProductsPage_NewFamily {
            get {
                return ResourceManager.GetString("ProductsPage_NewFamily", resourceCulture);
            }
        }

        public static string ProductsPage_FamilyCodePlaceholder {
            get {
                return ResourceManager.GetString("ProductsPage_FamilyCodePlaceholder", resourceCulture);
            }
        }

        public static string ProductsPage_FamilyDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("ProductsPage_FamilyDescriptionPlaceholder", resourceCulture);
            }
        }

        public static string Hours_EditTitle {
            get {
                return ResourceManager.GetString("Hours_EditTitle", resourceCulture);
            }
        }
        public static string Hours_NewTitle {
            get {
                return ResourceManager.GetString("Hours_NewTitle", resourceCulture);
            }
        }
        public static string Family_NewTitle {
            get {
                return ResourceManager.GetString("Family_NewTitle", resourceCulture);
            }
        }
        public static string Family_NamePlaceholder {
            get {
                return ResourceManager.GetString("Family_NamePlaceholder", resourceCulture);
            }
        }
        public static string Sync_FolderTitle {
            get {
                return ResourceManager.GetString("Sync_FolderTitle", resourceCulture);
            }
        }
        public static string Sync_FolderMessage {
            get {
                return ResourceManager.GetString("Sync_FolderMessage", resourceCulture);
            }
        }
        public static string Sync_Yes {
            get {
                return ResourceManager.GetString("Sync_Yes", resourceCulture);
            }
        }
        public static string Sync_NotNow {
            get {
                return ResourceManager.GetString("Sync_NotNow", resourceCulture);
            }
        }
        public static string Sync_ReportTitle {
            get {
                return ResourceManager.GetString("Sync_ReportTitle", resourceCulture);
            }
        }
        public static string Sync_ReportMessage {
            get {
                return ResourceManager.GetString("Sync_ReportMessage", resourceCulture);
            }
        }
        public static string Sync_Starting {
            get {
                return ResourceManager.GetString("Sync_Starting", resourceCulture);
            }
        }
        public static string Dashboard_TotalHours {
            get {
                return ResourceManager.GetString("Dashboard_TotalHours", resourceCulture);
            }
        }
        public static string Dashboard_DailyAverage {
            get {
                return ResourceManager.GetString("Dashboard_DailyAverage", resourceCulture);
            }
        }
        public static string Dashboard_WorkedDays {
            get {
                return ResourceManager.GetString("Dashboard_WorkedDays", resourceCulture);
            }
        }
        public static string Dashboard_TopClients {
            get {
                return ResourceManager.GetString("Dashboard_TopClients", resourceCulture);
            }
        }
        public static string Dashboard_TopFamilies {
            get {
                return ResourceManager.GetString("Dashboard_TopFamilies", resourceCulture);
            }
        }
        public static string Dashboard_HoursByMonth {
            get {
                return ResourceManager.GetString("Dashboard_HoursByMonth", resourceCulture);
            }
        }
        public static string Dashboard_HoursByFamily {
            get {
                return ResourceManager.GetString("Dashboard_HoursByFamily", resourceCulture);
            }
        }
        public static string Dashboard_Balance {
            get {
                return ResourceManager.GetString("Dashboard_Balance", resourceCulture);
            }
        }
        public static string Dashboard_Evolution {
            get {
                return ResourceManager.GetString("Dashboard_Evolution", resourceCulture);
            }
        }
        public static string Dashboard_Annual {
            get {
                return ResourceManager.GetString("Dashboard_Annual", resourceCulture);
            }
        }
        public static string Dashboard_RealHours {
            get {
                return ResourceManager.GetString("Dashboard_RealHours", resourceCulture);
            }
        }
        public static string Dashboard_IdealHours {
            get {
                return ResourceManager.GetString("Dashboard_IdealHours", resourceCulture);
            }
        }
        public static string Dashboard_ExtraHours {
            get {
                return ResourceManager.GetString("Dashboard_ExtraHours", resourceCulture);
            }
        }
        public static string Dashboard_Absences {
            get {
                return ResourceManager.GetString("Dashboard_Absences", resourceCulture);
            }
        }
        public static string Dashboard_AbsencesAccumulated {
            get {
                return ResourceManager.GetString("Dashboard_AbsencesAccumulated", resourceCulture);
            }
        }
        public static string Dashboard_SelectCollaborator {
            get {
                return ResourceManager.GetString("Dashboard_SelectCollaborator", resourceCulture);
            }
        }
        public static string Common_DeleteConfirmationTitle {
            get {
                return ResourceManager.GetString("Common_DeleteConfirmationTitle", resourceCulture);
            }
        }
        public static string Common_DeleteConfirmationMessage {
            get {
                return ResourceManager.GetString("Common_DeleteConfirmationMessage", resourceCulture);
            }
        }
        public static string Common_DeleteConfirmationMessageFormat {
            get {
                return ResourceManager.GetString("Common_DeleteConfirmationMessageFormat", resourceCulture);
            }
        }
        public static string Hours_SelectCollaborator {
            get {
                return ResourceManager.GetString("Hours_SelectCollaborator", resourceCulture);
            }
        }
        public static string Hours_Absence {
            get {
                return ResourceManager.GetString("Hours_Absence", resourceCulture);
            }
        }
        public static string Hours_SelectReason {
            get {
                return ResourceManager.GetString("Hours_SelectReason", resourceCulture);
            }
        }
        public static string Hours_NoClient {
            get {
                return ResourceManager.GetString("Hours_NoClient", resourceCulture);
            }
        }
        public static string Hours_Work {
            get {
                return ResourceManager.GetString("Hours_Work", resourceCulture);
            }
        }
        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }

        public static string Welcome_Connecting {
            get {
                return ResourceManager.GetString("Welcome_Connecting", resourceCulture);
            }
        }

        public static string Welcome_ConnectionFailed {
            get {
                return ResourceManager.GetString("Welcome_ConnectionFailed", resourceCulture);
            }
        }

        public static string Welcome_ConnectionError {
            get {
                return ResourceManager.GetString("Welcome_ConnectionError", resourceCulture);
            }
        }

        public static string Welcome_Title {
            get {
                return ResourceManager.GetString("Welcome_Title", resourceCulture);
            }
        }

        public static string Welcome_Subtitle {
            get {
                return ResourceManager.GetString("Welcome_Subtitle", resourceCulture);
            }
        }

        public static string Welcome_Description {
            get {
                return ResourceManager.GetString("Welcome_Description", resourceCulture);
            }
        }

        public static string Welcome_ChooseCompany {
            get {
                return ResourceManager.GetString("Welcome_ChooseCompany", resourceCulture);
            }
        }

        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }

        public static string Login_Welcome {
            get {
                return ResourceManager.GetString("Login_Welcome", resourceCulture);
            }
        }

        public static string Login_UserFound {
            get {
                return ResourceManager.GetString("Login_UserFound", resourceCulture);
            }
        }

        public static string Login_Subtitle {
            get {
                return ResourceManager.GetString("Login_Subtitle", resourceCulture);
            }
        }

        public static string Login_UsernamePlaceholder {
            get {
                return ResourceManager.GetString("Login_UsernamePlaceholder", resourceCulture);
            }
        }

        public static string Login_PasswordPlaceholder {
            get {
                return ResourceManager.GetString("Login_PasswordPlaceholder", resourceCulture);
            }
        }

        public static string Login_Button {
            get {
                return ResourceManager.GetString("Login_Button", resourceCulture);
            }
        }

        public static string Login_Biometric {
            get {
                return ResourceManager.GetString("Login_Biometric", resourceCulture);
            }
        }

        public static string Login_RememberMe {
            get {
                return ResourceManager.GetString("Login_RememberMe", resourceCulture);
            }
        }

        public static string Login_ForgotPassword {
            get {
                return ResourceManager.GetString("Login_ForgotPassword", resourceCulture);
            }
        }

        public static string Login_HaveCode {
            get {
                return ResourceManager.GetString("Login_HaveCode", resourceCulture);
            }
        }

        public static string Login_InternalReset {
            get {
                return ResourceManager.GetString("Login_InternalReset", resourceCulture);
            }
        }

        public static string Login_InvalidCredentials {
            get {
                return ResourceManager.GetString("Login_InvalidCredentials", resourceCulture);
            }
        }

        public static string Main_Logout {
            get {
                return ResourceManager.GetString("Main_Logout", resourceCulture);
            }
        }

        public static string Main_Dashboard {
            get {
                return ResourceManager.GetString("Main_Dashboard", resourceCulture);
            }
        }

        public static string Main_Clients {
            get {
                return ResourceManager.GetString("Main_Clients", resourceCulture);
            }
        }

        public static string Main_Products {
            get {
                return ResourceManager.GetString("Main_Products", resourceCulture);
            }
        }

        public static string Main_Hours {
            get {
                return ResourceManager.GetString("Main_Hours", resourceCulture);
            }
        }

        public static string Main_Services {
            get {
                return ResourceManager.GetString("Main_Services", resourceCulture);
            }
        }

        public static string Main_Theme {
            get {
                return ResourceManager.GetString("Main_Theme", resourceCulture);
            }
        }

        public static string Main_ThemeAuto {
            get {
                return ResourceManager.GetString("Main_ThemeAuto", resourceCulture);
            }
        }

        public static string Main_ThemeLight {
            get {
                return ResourceManager.GetString("Main_ThemeLight", resourceCulture);
            }
        }

        public static string Main_ThemeDark {
            get {
                return ResourceManager.GetString("Main_ThemeDark", resourceCulture);
            }
        }

        public static string Main_WelcomeTo {
            get {
                return ResourceManager.GetString("Main_WelcomeTo", resourceCulture);
            }
        }

        public static string Main_AdminAccess {
            get {
                return ResourceManager.GetString("Main_AdminAccess", resourceCulture);
            }
        }

        public static string Main_AdminUserPlaceholder {
            get {
                return ResourceManager.GetString("Main_AdminUserPlaceholder", resourceCulture);
            }
        }

        public static string Main_AdminPassPlaceholder {
            get {
                return ResourceManager.GetString("Main_AdminPassPlaceholder", resourceCulture);
            }
        }

        public static string Main_LogoutTitle {
            get {
                return ResourceManager.GetString("Main_LogoutTitle", resourceCulture);
            }
        }

        public static string Main_LogoutMessage {
            get {
                return ResourceManager.GetString("Main_LogoutMessage", resourceCulture);
            }
        }

        public static string Main_LogoutConfirm {
            get {
                return ResourceManager.GetString("Main_LogoutConfirm", resourceCulture);
            }
        }

        public static string Main_CloseTitle {
            get {
                return ResourceManager.GetString("Main_CloseTitle", resourceCulture);
            }
        }

        public static string Main_CloseMessage {
            get {
                return ResourceManager.GetString("Main_CloseMessage", resourceCulture);
            }
        }

        public static string Main_AccessDenied {
            get {
                return ResourceManager.GetString("Main_AccessDenied", resourceCulture);
            }
        }

        public static string Main_AdminRequired {
            get {
                return ResourceManager.GetString("Main_AdminRequired", resourceCulture);
            }
        }

        public static string Main_AdminEnterCredentials {
            get {
                return ResourceManager.GetString("Main_AdminEnterCredentials", resourceCulture);
            }
        }

        public static string Main_NoContent {
            get {
                return ResourceManager.GetString("Main_NoContent", resourceCulture);
            }
        }

        public static string Common_Back {
            get {
                return ResourceManager.GetString("Common_Back", resourceCulture);
            }
        }

        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }

        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }

        public static string Settings_SystemSettings {
            get {
                return ResourceManager.GetString("Settings_SystemSettings", resourceCulture);
            }
        }

        public static string Settings_Users {
            get {
                return ResourceManager.GetString("Settings_Users", resourceCulture);
            }
        }

        public static string Settings_UsersDesc {
            get {
                return ResourceManager.GetString("Settings_UsersDesc", resourceCulture);
            }
        }

        public static string Settings_Database {
            get {
                return ResourceManager.GetString("Settings_Database", resourceCulture);
            }
        }

        public static string Settings_DatabaseDesc {
            get {
                return ResourceManager.GetString("Settings_DatabaseDesc", resourceCulture);
            }
        }

        public static string Settings_FileServer {
            get {
                return ResourceManager.GetString("Settings_FileServer", resourceCulture);
            }
        }

        public static string Settings_FileServerDesc {
            get {
                return ResourceManager.GetString("Settings_FileServerDesc", resourceCulture);
            }
        }

        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }

        public static string Settings_LanguageDesc {
            get {
                return ResourceManager.GetString("Settings_LanguageDesc", resourceCulture);
            }
        }

        public static string Login_UseBiometric {
            get {
                return ResourceManager.GetString("Login_UseBiometric", resourceCulture);
            }
        }

        public static string Hours_TabSummary {
            get {
                return ResourceManager.GetString("Hours_TabSummary", resourceCulture);
            }
        }
        public static string Hours_TabList {
            get {
                return ResourceManager.GetString("Hours_TabList", resourceCulture);
            }
        }
        public static string Hours_TabCalendar {
            get {
                return ResourceManager.GetString("Hours_TabCalendar", resourceCulture);
            }
        }
        public static string Hours_DailySummary {
            get {
                return ResourceManager.GetString("Hours_DailySummary", resourceCulture);
            }
        }
        public static string Hours_NormalHours {
            get {
                return ResourceManager.GetString("Hours_NormalHours", resourceCulture);
            }
        }
        public static string Hours_ExtraHours {
            get {
                return ResourceManager.GetString("Hours_ExtraHours", resourceCulture);
            }
        }
        public static string Hours_Total {
            get {
                return ResourceManager.GetString("Hours_Total", resourceCulture);
            }
        }
        public static string Hours_Weekend {
            get {
                return ResourceManager.GetString("Hours_Weekend", resourceCulture);
            }
        }
        public static string Hours_NoRecords {
            get {
                return ResourceManager.GetString("Hours_NoRecords", resourceCulture);
            }
        }
        public static string Hours_SelectPeriod {
            get {
                return ResourceManager.GetString("Hours_SelectPeriod", resourceCulture);
            }
        }
        public static string Hours_PeriodToday {
            get {
                return ResourceManager.GetString("Hours_PeriodToday", resourceCulture);
            }
        }
        public static string Hours_PeriodThisWeek {
            get {
                return ResourceManager.GetString("Hours_PeriodThisWeek", resourceCulture);
            }
        }
        public static string Hours_PeriodThisMonth {
            get {
                return ResourceManager.GetString("Hours_PeriodThisMonth", resourceCulture);
            }
        }
        public static string Hours_PeriodLast30Days {
            get {
                return ResourceManager.GetString("Hours_PeriodLast30Days", resourceCulture);
            }
        }
        public static string Hours_CalendarMonth {
            get {
                return ResourceManager.GetString("Hours_CalendarMonth", resourceCulture);
            }
        }
        public static string Hours_LegendNormal {
            get {
                return ResourceManager.GetString("Hours_LegendNormal", resourceCulture);
            }
        }
        public static string Hours_LegendExtra {
            get {
                return ResourceManager.GetString("Hours_LegendExtra", resourceCulture);
            }
        }
        public static string Hours_Reason {
            get {
                return ResourceManager.GetString("Hours_Reason", resourceCulture);
            }
        }
        public static string Hours_Client {
            get {
                return ResourceManager.GetString("Hours_Client", resourceCulture);
            }
        }
        public static string Hours_Date {
            get {
                return ResourceManager.GetString("Hours_Date", resourceCulture);
            }
        }
        public static string Hours_Observations {
            get {
                return ResourceManager.GetString("Hours_Observations", resourceCulture);
            }
        }
        public static string Hours_SelectClient {
            get {
                return ResourceManager.GetString("Hours_SelectClient", resourceCulture);
            }
        }
        public static string Hours_RecordType {
            get {
                return ResourceManager.GetString("Hours_RecordType", resourceCulture);
            }
        }
        public static string Hours_SavedSuccess {
            get {
                return ResourceManager.GetString("Hours_SavedSuccess", resourceCulture);
            }
        }
        public static string Hours_ErrorSelectCollaborator {
            get {
                return ResourceManager.GetString("Hours_ErrorSelectCollaborator", resourceCulture);
            }
        }
        public static string Hours_ErrorSelectReason {
            get {
                return ResourceManager.GetString("Hours_ErrorSelectReason", resourceCulture);
            }
        }
        public static string Hours_ErrorEnterHours {
            get {
                return ResourceManager.GetString("Hours_ErrorEnterHours", resourceCulture);
            }
        }
        public static string Hours_ErrorSaving {
            get {
                return ResourceManager.GetString("Hours_ErrorSaving", resourceCulture);
            }
        }
        public static string Hours_ErrorOpeningPopup {
            get {
                return ResourceManager.GetString("Hours_ErrorOpeningPopup", resourceCulture);
            }
        }
    }
}
