using System.Collections.Generic;

namespace NAVIGEST.Shared.Helpers;

public static class CountryDialCodeData
{
    public sealed record DialCode(string Iso2, string Name, string Prefix);

    public static IReadOnlyList<DialCode> All { get; } = new List<DialCode>
    {
        new("PT", "Portugal", "+351"),
        new("ES", "Espanha", "+34"),
        new("FR", "França", "+33"),
        new("GB", "Reino Unido", "+44"),
        new("DE", "Alemanha", "+49"),
        new("IT", "Itália", "+39"),
        new("NL", "Países Baixos", "+31"),
        new("BE", "Bélgica", "+32"),
        new("CH", "Suíça", "+41"),
        new("US", "Estados Unidos", "+1"),
        new("CA", "Canadá", "+1"),
        new("BR", "Brasil", "+55"),
        new("MX", "México", "+52"),
        new("AR", "Argentina", "+54"),
        new("CL", "Chile", "+56"),
        new("CO", "Colômbia", "+57"),
        new("PE", "Peru", "+51"),
        new("AO", "Angola", "+244"),
        new("MZ", "Moçambique", "+258"),
        new("ZA", "África do Sul", "+27"),
        new("CN", "China", "+86"),
        new("JP", "Japão", "+81"),
        new("KR", "Coreia do Sul", "+82"),
        new("AU", "Austrália", "+61"),
        new("NZ", "Nova Zelândia", "+64"),
        new("IN", "Índia", "+91"),
        new("AE", "Emirados Árabes", "+971"),
        new("SA", "Arábia Saudita", "+966"),
        new("RU", "Rússia", "+7"),
        new("IE", "Irlanda", "+353"),
        new("DK", "Dinamarca", "+45"),
        new("SE", "Suécia", "+46"),
        new("NO", "Noruega", "+47"),
        new("FI", "Finlândia", "+358"),
        new("CZ", "República Checa", "+420"),
        new("PL", "Polónia", "+48"),
        new("RO", "Roménia", "+40"),
        new("HU", "Hungria", "+36"),
        new("SK", "Eslováquia", "+421"),
        new("SI", "Eslovénia", "+386"),
        new("HR", "Croácia", "+385"),
        new("GR", "Grécia", "+30"),
        new("TR", "Turquia", "+90"),
        new("IS", "Islândia", "+354"),
        new("EE", "Estónia", "+372"),
        new("LV", "Letónia", "+371"),
        new("LT", "Lituânia", "+370"),
        new("BG", "Bulgária", "+359"),
        new("LU", "Luxemburgo", "+352"),
        new("MC", "Mónaco", "+377"),
        new("AD", "Andorra", "+376"),
        new("LI", "Liechtenstein", "+423"),
        new("QA", "Catar", "+974"),
        new("KW", "Kuwait", "+965"),
        new("OM", "Omã", "+968"),
        new("EG", "Egipto", "+20"),
        new("TN", "Tunísia", "+216"),
        new("MA", "Marrocos", "+212"),
        new("NG", "Nigéria", "+234"),
        new("KE", "Quénia", "+254"),
        new("GH", "Gana", "+233"),
        new("ID", "Indonésia", "+62"),
        new("TH", "Tailândia", "+66"),
        new("MY", "Malásia", "+60"),
        new("PH", "Filipinas", "+63"),
        new("SG", "Singapura", "+65"),
        new("VN", "Vietname", "+84"),
        new("HK", "Hong Kong", "+852"),
        new("TW", "Taiwan", "+886"),
        new("PK", "Paquistão", "+92"),
        new("BD", "Bangladesh", "+880"),
        new("IL", "Israel", "+972"),
        new("IR", "Irão", "+98"),
        new("SY", "Síria", "+963"),
        new("LB", "Líbano", "+961"),
        new("JO", "Jordânia", "+962"),
        new("PS", "Palestina", "+970"),
        new("YE", "Iémen", "+967"),
        new("LK", "Sri Lanka", "+94"),
        new("NP", "Nepal", "+977"),
        new("MM", "Myanmar", "+95"),
    new("KH", "Camboja", "+855"),
    new("LA", "Laos", "+856"),
        new("KZ", "Cazaquistão", "+7"),
        new("UZ", "Uzbequistão", "+998"),
        new("KG", "Quirguistão", "+996"),
        new("TJ", "Tajiquistão", "+992"),
        new("TM", "Turquemenistão", "+993"),
        new("AZ", "Azerbaijão", "+994"),
        new("GE", "Geórgia", "+995"),
        new("AM", "Arménia", "+374"),
        new("BY", "Bielorrússia", "+375"),
        new("UA", "Ucrânia", "+380"),
        new("MD", "Moldávia", "+373"),
        new("BA", "Bósnia e Herzegovina", "+387"),
        new("MK", "Macedónia do Norte", "+389"),
        new("AL", "Albânia", "+355"),
        new("MT", "Malta", "+356")
    };
}
